name: Trigger Embed Service

on:
  push:
    branches:
      - main

jobs:
  trigger-embed:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Embed Service
        run: |
          curl -f -X POST https://apollo.staging.openfn.org/services/embed_docsite \
            -H "Content-Type: application/json" \
            -d '{
              "api_key": "${{ secrets.APOLLO_PROD_API_KEY }}"
            }'
