name: Embed docsite

on:
  push:
    branches:
      - main

jobs:
  trigger-embed:
    runs-on: ubuntu-latest
    steps:
      - name: Embed docs into staging
        env:
          APOLLO_STAGING_API_KEY: ${{ secrets.APOLLO_STAGING_API_KEY }}
        run: |
          curl -f -X POST https://apollo.staging.openfn.org/services/embed_docsite \
            -H "Content-Type: application/json" \
            -d "{ \
                "target": "postgres", \
                \"api_key\": \"$APOLLO_STAGING_API_KEY\" \
              }"
